batch_size_test: 22
batch_size_test_text: 150
batch_size_tta: 32
be_hard: true
be_pose_img: true
eda_p: 1
embed_dim: 2048
erasing_p: 0.6
h: 224
image_root: data/PAB/
itc_dp: 0.5
k_test: 128
k_tta: 4
label_smooth: 0.2
load_params: true
load_pretrained: true
mask_prob: 0.25
mask_whole_word: true
max_masks: 10
max_tokens: 56
max_words: 56
optimizer: {lr: 1e-05, lr_mult: 2, opt: adamW, weight_decay: 0.01}
pose_conv: true
sample_selection: top1
schedular: {epochs: 60, lr: 1e-05, num_warmup_steps: 500, sched: step}
score_temper: 1.0
skipgram_prb: 0.2
skipgram_size: 3
temp: 0.07
temperature: 0.03
test_file: data/PAB/annotation/test/attr.json
text_config: configs/config_bert.json
text_encoder: checkpoint/jizheng/bert-base-uncased
tta_file: data/PAB/annotation/test/attr.json
tta_model: ''
tta_steps: 1
uncertainty: diff_div_mean
uncertainty_coeffi: 0.01
uncertainty_i2t_temper: 1.0
uncertainty_t2i_temper: 1.0
uncertainty_temper: 1.0
uncertainty_temper_is_learnable: false
vision_config: configs/config_swinB.json
w: 224
